# The params.yaml file is commonly used in Machine Learning (ML) and Data Science projects to store hyperparameters, configurations, and settings in a structured and readable way.

# It is widely used in projects involving ML pipelines, MLOps, and automation tools like DVC (Data Version Control) and Hydra.
base:
    project:Deep learning

raw_data:
    data_src:data_source

load_data:
    num_classes: 4
    row_data: data_soure
    preprocessed_data: data/processed
    full_path: dlproject/data_source

train:
    split_ratio:0.80

model:
    name: VGG19
    trainable: False
    train_path: data/processed/train
    test_path: data/processed/test
    optimizer: adam   
    loss: categorical_crossentropy  
    metrics: ["accuracy"]
    epochs: 1
    # batch_size:32
    sav_dir: models/trained.h5

img_augment:
    rescale:1./255
    shear_range:0.2
    zoom_range:0.2
    horizontal_flip:True
    rotation_range:20
    batch_size:32
    class_mode:'categorical'

model_dir: models

mlflow_config:
    artiact_dir: artifacts
    experiment_name: deep_learning_VGG19
    run_name: mlops
    registered_model_name: deep_learning_VGG19
    remote_server_uri: http://172.0.0.1:5000
    
    
